name: Docs

on:
  push:
    branches: [ main ]
permissions:
  contents: write

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'adopt'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: "8.8"

      - name: Build documentation
        run: gradle dokkaHtmlMultiModule

      - name: Publish documentation
        uses: JamesIves/github-pages-deploy-action@releases/v4
        with:
          folder: build/dokka/htmlMultiModule
